### ISSUE TITLE
how to install vue-plugin or vuecomponent lib.

### ISSUE THREAD

**Issue by wuchuguang** [cucygh/vue-chrome-extension-example#1]
not support webpack, cant install vue-component lib.

**Comment by briangonzalez** [comment]
@wuchuguang which lib are you trying to install?

**Comment by wuchuguang** [comment]
vuex, vue-router, and so on.

**Comment by briangonzalez** [comment]
@wuchuguang take a look at https://github.com/eggplanetio/tidytab

it uses this repo and has all of those installed

**Comment by beupgo** [comment]
with npm you can install vue-plugin anyway and can edit webpack config if need
