### ISSUE TITLE
ENV is not defined

### ISSUE THREAD

**Issue by Spazer9** [cucygh/vue-chrome-extension-example#3]
EDITED:

This example doesn't work out of the box according the readme. I have unboxed it as it is - ran `npm-install` then `gulp --watch` . then dragged the resulting `dist/chrome` onto chrome. 

`popup.js` throws an error:

`Uncaught SyntaxError: Unexpected token import`

It seems like it's not even compiling the JS down to ES2015.

Also, it seems like "ENV" is not defined or accessible from either background.js or any other script.

`background.js:13 Uncaught ReferenceError: ENV is not defined
    at Object.<anonymous> (background.js:13)
    at Object.defineProperty.value (background.js:272)
    at __webpack_require__ (bootstrap 74cef87…:19)
    at Object.module.exports (bootstrap 74cef87…:39)
    at __webpack_require__ (bootstrap 74cef87…:19)
    at bootstrap 74cef87…:39
    at bootstrap 74cef87…:39`

**Comment by Spazer9** [comment]
I actually looked at /dist/chrome/scripts/app.js (which is generated by gulp & build)

It contains "import" which isn't really supported on browsers. screenshot: 

![](https://s3.amazonaws.com/snaps-bucket/2017/08/2eQRWTc/2017-08-03_16-35-09.png)

**Comment by beupgo** [comment]
please checkout the latest commit for this issue
